name: 'CI: Pull Request'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  install_deps:
    name: Install Dependencies and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.11

      - name: Print node version
        id: node-version
        run: |
          node_ver=$( node --version )
          echo "Node: ${node_ver:1}"
          echo "::set-output name=node_version::${node_ver:1}"

      - name: Print pnpm version
        id: pnpm-version
        run: |
          pnpm_ver=$( pnpm --version )
          echo "Node: ${pnpm_ver:1}"
          echo "::set-output name=pnpm_version::${pnpm_ver:1}"

      - name: Restore "node_modules" from cache
        id: cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: node_modules
          restore-keys: ${{ runner.os }}-node_modules
          key: ${{ runner.os }}-node-${{ steps.node-version.outputs.node_version }}-${{ steps.pnpm-version.outputs.pnpm_version}}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Save "node_modules" to cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: martijnhols/actions-cache/save@v3
        with:
          path: node_modules
          key: ${{ steps.cache.outputs.primary-key }}

  static_testing:
    name: Static Testing with SonarCloud
    runs-on: ubuntu-latest
    needs: install_deps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Static Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  static_testing_2:
    name: Static Testing with Snyk
    needs: install_deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  jobs:
    name: Jobs
    runs-on: ubuntu-latest
    needs: ['static_testing', 'static_testing_2']
    strategy:
      fail-fast: true
      matrix:
        job: ['test', 'build']
        test: [{ test1: 'test', test2: 'test2', test3: 'test3' }]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.11

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: main

      - name: Print node version
        id: node-version
        run: |
          node_ver=$( node --version )
          echo "Node: ${node_ver:1}"
          echo "::set-output name=node_version::${node_ver:1}"

      - name: Print pnpm version
        id: pnpm-version
        run: |
          pnpm_ver=$( pnpm --version )
          echo "Pnpm: ${pnpm_ver:1}"
          echo "::set-output name=pnpm_version::${pnpm_ver:1}"

      - name: Restore "node_modules" from cache
        uses: martijnhols/actions-cache/restore@v3
        with:
          path: node_modules
          restore-keys: ${{ runner.os }}-node_modules
          key: ${{ runner.os }}-node-${{ steps.node-version.outputs.node_version }}-${{ steps.pnpm-version.outputs.pnpm_version}}-${{ hashFiles('pnpm-lock.yaml') }}

      - run: npx nx affected --target=${{ matrix.job }} --parallel=1 --base=$NX_BASE --head=$NX_HEAD
      - run: echo '${{ matrix.test.test1 }} ${{ matrix.test.test2 }} ${{ matrix.test.test3 }}'
